name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install deps
      run: |
       sudo apt-get update
       sudo apt-get install -y qemu qemu-user-static
       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build the Docker image
      run: docker build . --file Dockerfile
